name: node.js Package
on:
  push:
    branches:
      - main
    
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version : 16
          registry-url: https://npm.pkg.github.com/
          scope: '@armennag'
      - run: npm install  
      - run | 
            touch emptyfile  
            gh api /orgs/ArmenNag/packages/npm/devopstest/versions 
            --paginate -q '.[].id' | tail -n +101 | xargs -n1 -I {} gh api 
            --method DELETE /orgs/ArmenNag/packages/npm/devopstest/versions/3 
            --input emptyfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
