
name: node.js Package
on:
  push:
    branches:
      - main
    
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version : 16
          registry: https://npm.pkg.github.com/
      
      - run: |
             
             npm unpublish devopstest@1.0.0
          
      - uses: actions/upload-artifact@v3
        with:
          name: logs
          path: home/runner/work/_temp
      
      
      
      
        env:
          NPM_TOKEN: ${GITHUB_TOKEN}
          NODE_AUTH_TOKEN: ${GITHUB_TOKEN}
      

        
