
name: node.js Package
on:
  push:
    branches:
      - main
    
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version : 16
          registry-url: https://npm.pkg.github.com/
          scope: '@armennag'
      
      - run: |
          echo '//https://npm.pkg.github.com/@armennag/:_authToken=${NPM_TOKEN}' > .npmrc
          npm config set registry https://npm.pkg.github.com/@armennag --loglevel silly 
          echo </home/runner/work/_temp/.npmrc
          npm unpublish devopstest@1.0.0 --force --loglevel silly
      
      
      
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      

        
