
name: node.js Package
on:
  push:
    branches:
      - main
   
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version : 16
          registry-url: https://npm.pkg.github.com/
          scope: '@armennag'
      - run: npm install
      
      - run: npm config set registry https://npm.pkg.github.com/
      - run: npm list --depth=0

      - run: npm unpublish "armennag/devopstest1.0.0" -f
      - run: echo /home/runner/work/_temp/.npmrc
        
