
name: node.js Package
on:
  push:
    branches:
      - main
    
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version : 16
          
      
      - run: |
             npm config set always-auth true
             npm config set _auth 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
             npm config set email armen.nagapetian@submittable.com
             
             npm unpublish devopstest@1.0.0
          
      - uses: actions/upload-artifact@v3
        with:
          name: logs
          path: home/runner/work/_temp
      
      
      
      
        env:
          NPM_TOKEN: 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
          NODE_AUTH_TOKEN: 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
      

        
