
name: node.js Package
on:
  push:
    branches:
      - main
    
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version : 16
          
      
      - run: |
             npm config set registry https://npm.pkg.github.com/@armennag 
             npm install @armennag/devopstest@1.0.3
             
          

      
      
      
      
        env:
          NPM_TOKEN: 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
          NODE_AUTH_TOKEN: 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
      

        
