
name: node.js Package
on:
  push:
    branches:
      - main
    
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version : 16
          registry-url: https://npm.pkg.github.com/
          scope: '@armennag'
      
      - run: |
             npm login --scope=@armennag --registry=https://npm.pkg.github.com/

             npm unpublish devopstest@1.0.0 --registry https://npm.pkg.github.com/@armennag
          
      - uses: actions/upload-artifact@v3
        with:
          name: logs
          path: home/runner/work/_temp
      
      
      
      
        env:
          NPM_TOKEN: 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
          NODE_AUTH_TOKEN: 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
      

        
