
name: node.js Package
on:
  push:
    branches:
      - main
    
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version : 16
          registry-url: https://npm.pkg.github.com/
          scope: '@armennag'
      - run: npm install  
      - run :  npm install @armennag/devopstest@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
