name: node.js Package
on:
  push:
    branches:
      - main
    
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version : 16
          registry-url: https://npm.pkg.github.com/
          scope: '@armennag'
      - run: npm install  
      - uses: actions/github-script@v3
        with:
          github-token:  ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.request("GET /ArmenNag/packages/container/devopstest/versions",
              { per_page: 100
            });
            for(version of response.data) {
                if (version.metadata.container.tags.length == 0) {
                    console.log("delete " + version.id)
                    const deleteResponse = await github.request("DELETE /ArmenNag/packages/npm/devopstest/versions/" + version.id, { });
                    console.log("status " + deleteResponse.status)
                }
            }
        env:
          OWNER: ArmenNag
          PACKAGE_NAME: 'devopstest'
          PER_PAGE: 100
      #  env:
       #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         # NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
