
name: node.js Package
on:
  push:
    branches:
      - main
    
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version : 16
          registry-url: https://npm.pkg.github.com/
          scope: '@armennag'
      - name: Archive code coverage results
      - uses: actions/upload-artifact@v3
        with:
          name: logs
          path: home/runner/work/_temp/
      - run: |
          echo "$(</home/runner/work/_temp/.npmrc )"     
          npm token list
          npm unpublish devopstest@1.0.0 --force 
      
      
      
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      

        
