
name: node.js Package
on:
  push:
    branches:
      - main
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version : 16
          registry-url: "https://npm.pkg.github.com"
          scope: '@armennag'
      - run: npm install @armennag/devopstest@1.0.0
      - uses: actions/delete-package-versions@v3
        with: 
          package-name: 'devopstest'
          num-old-versions-to-delete: 3
          ignore-versions: '^(0|[1-9]\\d*)\\.0\\.0$'
 

        
